### ISSUE TITLE
dispatch status 

### ISSUE THREAD

**Issue by CinecaElearning** [LearningLocker/xAPI-Recipe-Emitter#31] opened 2016-03-25 18:07 UTC
**Motive**
logstore_xapi has no return from the emitter about the connection and the dispatch status.

**Result**
a last_action_result key is added to the statements array which are returned to the logstore_xapi.

**Additional information**
{{additionalInfo}}

**Comment by ryansmith94** [comment] 2016-03-25 18:46
Not a fan of adding a non numeric key to a numerically indexed array. Either the LRS response needs to be returned or some other solution needs to be made. This is essentially a duplicate of #26 so I'm closing this for that reason. The discussion may be continued in that issue instead.

**Closed** 2016-03-25 18:46 UTC
Labels: priority:low, status:unconfirmed, type:enhancement
